# Generated by Django 3.0.7 on 2020-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantra',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantras.Group'),
        ),
    ]
